version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: guapo_postgresql_1
      APP_PORT: 5532
  
  postgresql:
    image: library/postgres:17.2@sha256:fe4efc6901dda0d952306fd962643d8022d7bb773ffe13fe8a21551b9276e50c
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5532:5532"
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: $APP_PASSWORD
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5532
    
