version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: guapo-postgresql
      APP_PORT: 5432
  
  web:
    image: postgres/postgres@sha256:994cc3113ce004ae73df11f0dbc5088cbe6bb0da1691dd7e6f55474202a4f211
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/postgres-data:/var/lib/postgresql/data
    environment:
      # PostgreSQL kullanıcı bilgileri
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: $APP_PASSWORD
      POSTGRES_DB: postgres
    
