version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: guapo_postgresql_1
      APP_PORT: 5532
  
  web:
    image: postgres:latest@sha256:810c36706d001955d088d9ab907e2d5b9937ecafb23e56aa01073fdafad6f4a4
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      # PostgreSQL kullanıcı bilgileri
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: "$APP_PASSWORD"
      POSTGRES_DB: postgres
    
